name: Unit Test Workflow

on: [push, pull_request]

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup MATLAB
      uses: matlab-actions/setup-matlab@v1

    - name: Run tests
      uses: matlab-actions/run-tests@v1
      with:
        source-folder: tests
