name: Unit Test Workflow

on: [push, pull_request]

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MATLAB
      uses: matlab-actions/setup-matlab@v2
    
    - name: Run setup script
      uses: matlab-actions/run-command@v2
      with:
        command: "run('setup');"

    - name: Run tests
      uses: matlab-actions/run-tests@v2
      with:
        source-folder: tests
